kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30102
        hostPort: 30102
  - role: worker
    extraPortMappings:
      - containerPort: 30102
        hostPort: 30103
  - role: worker
    extraPortMappings:
      - containerPort: 30102
        hostPort: 30104
      
     