apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany

  storageClassName: nfs
  nfs:
    server: 20.212.250.65
    path: /srv/nfs/k8s-data    
