# kind-istio-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: istio-lab
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80  # Maps to Istio ingressgateway HTTP
        hostPort: 8088
        protocol: TCP
      - containerPort: 32443  # Maps to Istio ingressgateway HTTPS
        hostPort: 8443
        protocol: TCP
  - role: worker
#I will map only cp