apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 20.212.250.65
    path: /exports/k8s-data   