apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: wp-pv
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 20.212.250.65
    path: /exports/wordpress-data