apiVersion: v1
kind: Service
metadata:
  name: wp-service
spec:
  selector:
    app: wp-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30102
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deployment
  labels:
    app: wp-pod
spec:
  selector:
    matchLabels:
      app: wp-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wp-pod
    spec:
      containers:
      - image: wordpress:6.2.1-apache
        name: wordpress
        command: ["sh", "-c", "chown -R 33:33 /var/www/html"]
        env:
        - name: WORDPRESS_DB_HOST
          value: wp-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DB_NAME
          value: wordpress
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pvc